### ISSUE TITLE
lan upnp doesnt work after some time

### ISSUE THREAD

**Issue by yvtss** [jredfox/lanupnp#8]
Hola brother! Thank You so much for your mod, he is so great!

After some time of playing FTB Infinity Evolved(1.7.10 version) with my friend through ur coolest mod ever we cant continue coz something went wrong and now we have issue like "Connection timed out: no further information"

Me and my friend tried to enable DMZ, port forwarding and enabling UPNP in our routers, change our network types to private in windows, opened minecraft as admin, disable firewall, and tried to add java and minecraft to exceptions in FW, but it doesnt work

So I beg u to help us, coz we just cant play anymore

Thank u so much

**Comment by jredfox** [comment]
Are you on Xfinity 2020-2023 router if so it's a known issue from them where you have to manually port forward any application call them to get it fixed
Disable Double NAT if enabled this will cause not only lag but lanupnp to not work correctly

Did you give out the correct IP from canyouseeme.org `ip:port`
If your on a lan world and are connecting on the same network you use your ipv4 not your public ip
try a different port `25565 sometimes won't work on a macOs for some odd reason`

remove all javaw.exe & java.exe from your firewall
readd all java.exe & javaw.exe on both **PUBLIC** and **PRIVATE** networks

make sure **OPEN TO NET** not **OPEN TO LAN**

**Comment by jredfox** [comment]
if the above doesn't work does removing all other mods except lanup solve the issue? It's very possible another mod is overriding the gui so the code isn't even executed

**Comment by yvtss** [comment]
Double NAT are disabled
IP was correct, but it changing after reloading router(or after some time)
We arent on same network so we are using public ip
World was opened to **NET**

So we removed java.exe and javaw.exe from firewall

We will try another ports. Btw, how other mods can override the gui, if everything was fine before?

The only suspicious thing: this happened after my friend downloaded WoW Cataclysm, can it be the reason of issue? like something in network or in PC are conflicting with upnp connection?

**Comment by jredfox** [comment]
canyouseeme.org with your opened port does it say success?
GuiOpenEvent can override guis same how my mod does it
IPs change all the time you have to update your friend your current public ip address if it changes. You have to pay the IPS for an ip that doesn't change

**Comment by yvtss** [comment]
canyouseeme.org says: **Connection refused**, in game, it says "port opened"

I think this error can be cause my friend are from Russia, they are have some troubles with sites, is there any other ways to check opened ports?

We tried to check port on portchecktool.com and it says the same **connection refused**

I tried to open server by myself  on modpack and on forge with only your mod and canyouseeme.org says the same error

We tried at port 49692, not 25565 and it still not working

**Comment by jredfox** [comment]
> refused

if it says refused nothing is going to work. you need to try and reset your internet settings back to default as you played with another setting and it no longer works.

then you have to 
- Enable UPNP
- Enable Port Forwarding
- Enable Port Triggering
- Disable DMZ (it's a firewall)
- Add java.exe & javaw.exe an exception to your firewall both public and private

Again try with just the mod itself as well

**Comment by yvtss** [comment]
Ok, 

UPNP enabled
Port Forwarding enabled
Port Triggering enabled
DMZ disabled
java.exe & javaw.exe added to exception with public and private marks

Also with just this mod doesnt work

**Comment by jredfox** [comment]
> Ok,
> 
> UPNP enabled Port Forwarding enabled Port Triggering enabled DMZ disabled java.exe & javaw.exe added to exception with public and private marks
> 
> Also with just this mod doesnt work

It appears to work for me. I would try and contact your Internet Service Provider (ISP) on why UPNP doesn't work. I know that it uses SOAP which relies on a web library which may be blocked from your ISP http://schemas.xmlsoap.org/soap/envelope/ which seems to link to http://www.w3.org/2001/XMLSchema
There is also a small chance the the lanupnp library I used has a bug. maybe you could find something in your log file

**Comment by jredfox** [comment]
@yvtss if your friend can't join your world from bedrock edition either then it's not an issue with the mod it's an issue with your ISP or internet box configuration settings.

**Comment by yvtss** [comment]
there is no useful info in log file
<img width="620" alt="Screenshot_1" src="https://github.com/jredfox/lanupnp/assets/168357389/3716b3c0-3dc3-4cdf-9dd0-6b5b22361bc6">

**Comment by jredfox** [comment]
Test minecraft bedrock I bet you minecraft bedrock edition doesn't work either

**Comment by jredfox** [comment]
Assuming issue also occurs without the mod as you didn't reply
